name: Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          arguments: build
          
      - name: Ensure src/main/resources directory exists
        run: mkdir -p src/main/resources  # 디렉토리 없으면 생성
          
      - name: Create application.properties from GitHub Secrets
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties
          echo "✅ application.properties 생성 완료"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # ✅ 5. Gradle 빌드 (bootJar 생성)
      - name: Build with Gradle
        run: ./gradlew clean bootJar
        
      # ✅ 6. Docker 이미지 빌드
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/antique-app .

      # ✅ 7. DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # ✅ 8. Docker 이미지 푸시
      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/antique-app

  deploy:
    needs: build
    runs-on: self-hosted  # EC2에서 실행됨

    steps:
      # ✅ 1. 최신 Docker 이미지 Pull
      - name: Pull Latest Docker Image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/antique-app

      # ✅ 2. 기존 컨테이너 중지 및 삭제 (있다면)
      - name: Stop and Remove Old Container
        run: |
          sudo docker stop antique-app || true
          sudo docker rm antique-app || true

      # ✅ 3. 새로운 컨테이너 실행
      - name: Run New Docker Container
        run: |
          sudo docker run -d \
            --name antique-app \
            -p 8080:8080 \
            --restart always \
            ${{ secrets.DOCKERHUB_USERNAME }}/antique-app

      # ✅ 4. 불필요한 Docker 이미지 정리
      - name: Clean Up Unused Docker Images
        run: sudo docker system prune -f
